### ISSUE TITLE
> I assume you can't replace the `${colorlist}` variable with a Java collection type as the `.variableReplace()` method of docx4j has the following signature `public void variableReplace(java.util.Map<String, String> mappings) throws JAXBException, Docx4JException` and is therefor expecting a `Map<String, String>`.

### ISSUE THREAD

**Issue by sathish38** [rieckpil/blog-tutorials#11]
> I assume you can't replace the `${colorlist}` variable with a Java collection type as the `.variableReplace()` method of docx4j has the following signature `public void variableReplace(java.util.Map<String, String> mappings) throws JAXBException, Docx4JException` and is therefor expecting a `Map<String, String>`.
> 
> If you just want to render the content of your List, you can do the following:
> 
> ```
>  variables.put("colorlist", Arrays.asList("blue", "red", "white").stream().collect(Collectors.joining(", ")));
> ```
> 
> and the output on the document should be: `blue, red, white`.
> 
> Otherwise please have a look at the [library](https://github.com/plutext/docx4j) itself or ask the question again on [StackOverflow](https://stackoverflow.com/).

Hi rieckpil,
I want to iterate it by one by one like this
1.blue
2.red
3.white
what I want to do change in my template so far I used the foreach in the template but it doesnt works

_Originally posted by @sathish38 in https://github.com/rieckpil/blog-tutorials/issues/9#issuecomment-565975507_

**Comment by rieckpil** [comment]
duplicate for https://github.com/rieckpil/blog-tutorials/issues/9.  Please have a look at the library itself or ask the question again on StackOverflow.
