### ISSUE TITLE
Can not get client used for request

### ISSUE THREAD

**Issue by lulseged** [rieckpil/blog-tutorials#12]
Hi

I have implemented a ClientResponseFilter interface to handle a 302(redirection) response and registered it in to RestClientBuilder. I can't get the client, it returns always null.

public class FollowRedirectInterceptor implements ClientResponseFilter

{
    @Override
    public void filter(ClientRequestContext clientRequestContext, ClientResponseContext clientResponseContext) throws IOException 
	{

        if (clientResponseContext.getStatusInfo().getFamily().equals(Response.Status.Family.REDIRECTION)) 
		{
            Client client = clientRequestContext.getClient();
            WebTarget target = client.target(clientResponseContext.getLocation());
            Response response = target.request(clientRequestContext.getMediaType()).method(clientRequestContext.getMethod());

            clientResponseContext.setEntityStream((InputStream) response.getEntity());
            clientResponseContext.setStatusInfo(response.getStatusInfo());
            clientResponseContext.setStatus(response.getStatus());
        }
    }
}

**Comment by rieckpil** [comment]
thanks for opening the issue here. Can you please provide more information about your project setup and how you MP RestClient looks like?

As this is not 100% related to the post on my blog, I can't guarantee to find time in the next days, so posting it in parallel on StackOverflow might make sense.

**Comment by rieckpil** [comment]
closed due to inactivity.

**Comment by lulseged** [comment]
ok

**Comment by rieckpil** [comment]
Hey @lulseged, I never heard back from you so that's why I closed the issue. Could you solve this in the meantime?

**Comment by lulseged** [comment]
Hi

I could not solve it. The problem lies on the RestClientBuilder from microprofile. It is my guess. The 1. RestClientBuilder uses a client to call a REST API.
2. REST API respondes with 302 and a location is in the response as the standard says.
3. My filter catches the 302 response and need to use the location in the response to make a new request.

But at this time the RestClient have lost the client that was used in the first request(1).
Client client = clientRequestContext.getClient(); (here client is null).

[FollowRedirectInterceptor.java.txt](https://github.com/rieckpil/blog-tutorials/files/4582687/FollowRedirectInterceptor.java.txt)

RestClientBuilder restClientBuilder = RestClientBuilder.newBuilder();
restClientBuilder.register(FollowRedirectInterceptor.class);

I will submit a ticket to MP.
