### ISSUE TITLE
Testcontainers with SpringBoot 2.3.3 Junit 5 "MySQLR2DBCDatabaseContainer" Example

### ISSUE THREAD

**Issue by sirAlexanderT** [rieckpil/blog-tutorials#19]
@rieckpil how can I achieve the same thing but using "org.testcontainers.containers.MySQLR2DBCDatabaseContainer" in a springboot test.
Hopefully something along what has been demonstrated here: https://rieckpil.de/howto-write-spring-boot-integration-tests-with-a-real-database/

**Comment by rieckpil** [comment]
Hey @sirAlexanderT,

the issue tracker for this repository focuses on bugs related to the projects in it.

I'd like to help you, but therefore please create a question on StackOverflow and provide more information on what you already tried and what is not working as expected. In this way, all other developers benefit from the answer and also other people can help. You can link the URL question to StackOverflow here in this issue and I will have a look at it.
