### ISSUE TITLE
TestContainers instantiation - Deprecated constructor 

### ISSUE THREAD

**Issue by JoeSeff** [rieckpil/blog-tutorials#26]
1. Pull the code
2. Run the test in testcontainers-youtube-series

## Context (Environment)
Java 11
Ubuntu 20.04

## Solution
Change the constructor and provide the image name.

![image](https://user-images.githubusercontent.com/3692453/108687623-fde81b80-7507-11eb-929a-cd7e25737d25.png)

**Comment by rieckpil** [comment]
thanks a lot for this finding @JoeSeff - I must have overseen this when bumping the Testcontainers version. If you want you can contribute and fix it :)

**Comment by rieckpil** [comment]
closed due to inactivity - feel free to reopen anytime.
