### ISSUE TITLE
Question: Customize an auto-generated WebClient

### ISSUE THREAD

**Issue by rieckpil** [rieckpil/blog-tutorials#30]
Follow-up from Val on https://rieckpil.de/customize-spring-webclient-with-webclientcustomizer/

So, I have this code automatically generated by open-api:

`ApiClient.java`

```
…
public ApiClient() {
…
  WebClient.Builder webClient = WebClient.builder().exchangeStrategies(strategies);
  this.webClient = return webClient.build();
}

```

I cannot edit this code.

In a service, I’d like to call

`ApiClient client = new ApiClient();`

and get automatically a list of filters attached. Let’s say I want the same filters you show in this page, logResponse and logRequest. Because filters can only be attached to the builder and not after WebClient creation, and because the WebClient creation is part of a generated code that I cannot edit. I was stuck. Do you say that I can get what I want by

1. Adding the WebClientCustomizer

```
@Component
public class ResponseLoggingCustomizer implements WebClientCustomizer {


  @Override
  public void customize(WebClient.Builder webClientBuilder) {
    webClientBuilder.filter(logResponse());
    webClientBuilder.filter(logRequest());
   }

```

2. Creating this bean

```
@Bean
@Scope(“prototype”)
@ConditionalOnMissingBean
public Builder webClientBuilder(ObjectProvider customizerProvider) {
  Builder builder = WebClient.builder();
  customizerProvider.orderedStream().forEach((customizer) -> {
    customizer.customize(builder);
  });
  return builder;
}
```
I guess I miss something, right?

**Comment by rieckpil** [comment]
Thanks for providing more detailed information Val! Now I totally get what the issue is.

In your example, you can mutate and apply filters/customize the `WebClient` afterward using the `.mutate()` functionality of the `WebClient`.

For this solution to work, you need to have access to the internal `WebClient` of your auto-generated `ApiClient`. A getter + setter would be perfect.

Something like the following should work:

```
ApiClient client = new ApiClient();

WebClient modifiedWebClient = client.getWebClient().mutate().apply(CUSTOMIZER).exchangeFunctions(FUNCTION).build();
client.setWebClient(modifiedWebClient);
```

In case the `ApiClient` doesn't expose its internal, I guess there's now way to adjust the `WebClient`.

**Comment by vstroeder** [comment]
Thank you for responding rieckpil.
Unfortunately the WebClient is not exposed neither a getter neither a setter. 
The solution would probably to propose to openapi to expose it but because of lack of time I'll juste use openapi with resttemplate, the generated code of ApiClient use a @Autowired constructor so I can provide restTemplate using @Bean...
Thanks again for your help!

**Comment by rieckpil** [comment]
Okay, great to hear that you have a _good enough_ alternative that works for you :)
