### ISSUE TITLE
Issue with JSON-B and JAXB

### ISSUE THREAD

**Issue by rieckpil** [rieckpil/blog-tutorials#4]
Extracted from a comment on blog post: https://rieckpil.de/whatis-json-binding-json-b/

Let me give an example:

I have created a JAXB object called PersonType:
```
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = “person-type”, propOrder = {
“firstName”,
“lastName”,
“age”,
“sex”
})
public class PersonType implements Serializable {

@XmlElement(name = “first-name”, required = true)
private String firstName;

@XmlElement(name = “last-name”, required = true)
private String lastName;

private int age;

@XmlElement(required = true)
@XmlSchemaType(name = “string”)
private SexType sex;

// getter and setter
}
```
I created a PersonType object and serialized it to JSON:
```
PersonType personType = new PersonType();
personType.setFirstName(“Lulseged”);
personType.setLastName(“Zerfu”);
personType.setAge(90);
personType.setSex(SexType.MALE);

Jsonb jsonb = JsonbBuilder.create();
System.out.println(jsonb.toJson(personType));

The result is:
{
“age”: 90,
“firstName”: “Lulseged”,
“lastName”: “Zerfu”,
“setAge”: true,
“setFirstName”: true,
“setLastName”: true,
“setSex”: true,
“sex”: “MALE”
}
```
What I expected to see was:
```
{
“age”: 90,
“firstName”: “Lulseged”,
“lastName”: “Zerfu”,
“sex”: “MALE”
}
```
I have to get ride of the sets:
```
“setAge”: true,
“setFirstName”: true,
“setLastName”: true,
“setSex”: true,
```
It works if the PersonType class was a plain old JAVA object.

By the way, I wonder why there is no JAXB in MicroProfile or even Jakarta has not updated it.

Thank you for your help.

**Comment by lulseged** [comment]
Is this a bug?

**Comment by rieckpil** [comment]
Hey @lulseged, yes it is weird to see the getters and setters in the result JSON. Are you the original author of the comment on my blog? Could you provide the full `PersonType` class here?

**Comment by lulseged** [comment]
Hej

Yes I am the original author of this comment.

I have also included plan old java objects.

tank you.

BR
Lulseged

________________________________

**Comment by rieckpil** [comment]
@lulseged where did you add the code? I can't see it in your last comment. Can you publish your project to GitHub or is it a private one?

**Comment by lulseged** [comment]
It was attached with previous e-mail. I put it here as a text. It is not private but it was an example that I just created to show what is going wrong when serializing JAXB Object to JSON:
----------------------------------------------------------------------------------------------
package palc.person.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;

/**
* <p>Java class for person-type complex type.
*
* <p>The following schema fragment specifies the expected content contained within this class.
*
* <pre>
* &lt;complexType name="person-type"&gt;
*   &lt;complexContent&gt;
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
*       &lt;sequence&gt;
*         &lt;element name="first-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
*         &lt;element name="last-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
*         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
*         &lt;element name="sex" type="{urn:palc:person:v1}sex-type"/&gt;
*       &lt;/sequence&gt;
*     &lt;/restriction&gt;
*   &lt;/complexContent&gt;
* &lt;/complexType&gt;
* </pre>
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "person-type", propOrder = {
        "firstName",
        "lastName",
        "age",
        "sex"
})
public class PersonType implements Serializable {

    @XmlElement(name = "first-name", required = true)
    private String firstName;

    @XmlElement(name = "last-name", required = true)
    private String lastName;

    private int age;

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    private SexType sex;

    /**
     * Gets the value of the firstName property.
    *
     * @return possible object is
     * {@link String }
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFirstName(String value) {
     this.firstName = value;
    }

    public boolean isSetFirstName() {
        return (this.firstName != null);
    }

    /**
     * Gets the value of the lastName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    public boolean isSetLastName() {
        return (this.lastName != null);
    }

    /**
     * Gets the value of the age property.
     */
    public int getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     */
    public void setAge(int value) {
        this.age = value;
    }

    public boolean isSetAge() {
        return true;
    }

    /**
     * Gets the value of the sex property.
     *
     * @return possible object is
     * {@link SexType }
     */
    public SexType getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     *
     * @param value allowed object is
     *              {@link SexType }
     */
    public void setSex(SexType value) {
        this.sex = value;
    }

    public boolean isSetSex() {
        return (this.sex != null);
    }
}
package palc.person.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
* <p>Java class for sex-type.
*
* <p>The following schema fragment specifies the expected content contained within this class.
* <p>
* <pre>
* &lt;simpleType name="sex-type"&gt;
*   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
*     &lt;enumeration value="FEMALE"/&gt;
*     &lt;enumeration value="MALE"/&gt;
*   &lt;/restriction&gt;
* &lt;/simpleType&gt;
* </pre>
*/
@XmlType(name = "sex-type")
@XmlEnum
public enum SexType {

    FEMALE,
    MALE;

    public String value() {
        return name();
    }

    public static SexType fromValue(String v) {
        return valueOf(v);
    }
}
package palc.person.v1;

import java.io.Serializable;

public class PersonType implements Serializable {

    private String firstName;

    private String lastName;

    private int age;

    private SexType sex;

    /**
     * Gets the value of the firstName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    public boolean isSetFirstName() {
        return (this.firstName != null);
    }

    /**
     * Gets the value of the lastName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    public boolean isSetLastName() {
        return (this.lastName != null);
    }

    /**
     * Gets the value of the age property.
     */
    public int getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     */
    public void setAge(int value) {
        this.age = value;
    }

    public boolean isSetAge() {
        return true;
    }

    /**
     * Gets the value of the sex property.
     *
     * @return possible object is
     * {@link SexType }
     */
    public SexType getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     *
     * @param value allowed object is
     *              {@link SexType }
     */
    public void setSex(SexType value) {
        this.sex = value;
    }

    public boolean isSetSex() {
        return (this.sex != null);
    }
}
package palc.person.v1;

public enum SexType {

    FEMALE,
    MALE;

    public String value() {
        return name();
    }

    public static SexType fromValue(String v) {
        return valueOf(v);
    }
}
----------------------------------------------------------------------------------------------

**Comment by rieckpil** [comment]
Thanks @lulseged for adding the code. For figuring out what's going wrong, there I need more information about the runtime of your application. Which Java/Jakarta EE version, your configuration, further dependencies... It would be perfect if you could upload your sample application to a GitHub repository so that I can fork it and check the issue.

**Comment by lulseged** [comment]
I have created a simple project(Not Java EE project). I have been playing around and found that there are isSetxxx methods that creates this issue. If I remove these isSetXXX methods then it works fine.

You can import to your favorite IDE and run the unit tests that are included in this project.

[testingjson.zip](https://github.com/rieckpil/blog-tutorials/files/3841511/testingjson.zip)

**Comment by rieckpil** [comment]
Yes, the issue comes from the `isXYZ` methods. These are usually used only together with boolean values of a POJO like the following:

```java
private boolean disabled;

public boolean isDisabled() {
     return disabled;
}

public void setDisabled(boolean disabled) {
     this.disabled = disabled;
}
```

as you use them JSON-B thinks they represent a boolean field of your `PersonType` class.

I can think of three possible solutions for fixing this:

1. Remove the `isXYZ` for all non-boolean fields. Do you really need them?
2. Use @JsonbTransient annotation on your `isXYZ` methods:
```java
@JsonbTransient
public boolean isSetAge() {
     return true;
}
```

3. Rename your `isXYZ` so they don't fit into the convention for boolean fields like:
```java
public boolean checkLastNameIsSet() {
        return (this.lastName != null);
}
```

Hope this helps :)

**Comment by lulseged** [comment]
I will use @JsonbTransient on those methods. This methods are generated by JAXB and they are helpful in some cases.
Thank you.
