### ISSUE TITLE
Unable to login after successful sign up 

### ISSUE THREAD

**Issue by msafiri1** [rieckpil/blog-tutorials#6]
WEB9102: Web Login Failed: com.sun.enterprise.security.auth.login.common.LoginException: Login failed: Failed jdbc login for Emmanuel.|#]
  
Thats the error I find whenever I try to login after successful sign up 
The following is my full code
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.loginView;
/**
 *
 * @author Emmanuel Msafiri Phiri
 */
import com.cims2019EJB.UserEJB;
import com.cims2019Entity.User;
import javax.annotation.ManagedBean;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.security.Principal;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
//import javax.faces.bean.ManagedBean;
//import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

@Named("loginView")
@ManagedBean
@SessionScoped
public class LoginView implements Serializable {

    private static final long serialVersionUID = 3254181235309041386L;
    private static Logger log = Logger.getLogger(LoginView.class.getName());
    @Inject
    private UserEJB userEJB;
    private String username;
    private String password;
    private User user;

    public String login() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        try {
            request.login(username, password
            );
        } catch (ServletException e) {
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Login Failed!", null));
            return "login.xhtml";
        }
        Principal principal = request.getUserPrincipal();
        this.user = userEJB.findUserById(principal.getName());
        log.log(Level.INFO, "Authentication done for user: {0}", principal.getName());
        ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
        Map<String, Object> sessionMap = externalContext.getSessionMap();
        sessionMap.put("User", user);   
        if (request.isUserInRole("users")) {     
            return "/user/sc.xhtml?faces-redirect=true";
        } else if (request.isUserInRole("admin")) {
                return "/admin/admin.xhtml?faces-redirect=true";
            }    
         else if (request.isUserInRole("SC_user")) {
                return "/SC_user/privatepage?faces-redirect=true";
            }
         else if (request.isUserInRole("Cardseb_user")) {
                return "/Cardseb_user/privatepage?faces-redirect=true";
            }
         else{
             return "login.xhtml";
        }
    }
    public String logout() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        try {
            this.user = null;
            request.logout();
            // clear the session
            ((HttpSession) context.getExternalContext().getSession(false)).invalidate();
        } catch (ServletException e) {
            log.log(Level.SEVERE, "Failed to logout user!", e);
        }
        return "/login.xhtml?faces-redirect=true";
    }

    public User getAuthenticatedUser() {
        return user;
    }

    public static Logger getLog() {
        return log;
    }

    public static void setLog(Logger log) {
        LoginView.log = log;
    }

    public UserEJB getUserEJB() {
        return userEJB;
    }

    public void setUserEJB(UserEJB userEJB) {
        this.userEJB = userEJB;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    public User getUser() {
        return user;
    }
    public void setUser(User user) {
        this.user = user;
    }
    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }
}

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cims201SecurityEntity;

import com.cims2019EJB.UserEJB;
import com.cims2019Entity.User;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.ManagedBean;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.faces.event.ComponentSystemEvent;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author LOGIMATE USER
 */
@Named(value="registerView")
@ManagedBean
@SessionScoped
public class RegisterView implements Serializable {
	private static final long serialVersionUID = 1685823449195612778L;
	private static Logger log = Logger.getLogger(RegisterView.class.getName());
	@Inject
	private UserEJB userEJB;
	private String username;
	private String email;
	private String password;
	private String confirmPassword;
	public void validatePassword(ComponentSystemEvent event) {
		FacesContext facesContext = FacesContext.getCurrentInstance();
		UIComponent components = event.getComponent();
               //get password
		UIInput uiInputPassword = (UIInput) components.findComponent("password");
		String password = uiInputPassword.getLocalValue() == null ? "" : uiInputPassword.getLocalValue().toString();
		String passwordId = uiInputPassword.getClientId();
		// get confirm password
		UIInput uiInputConfirmPassword = (UIInput) components.findComponent("confirmpassword");
		String confirmPassword = uiInputConfirmPassword.getLocalValue() == null ? ""
				: uiInputConfirmPassword.getLocalValue().toString();
		// Let required="true" do its job.
		if (password.isEmpty() || confirmPassword.isEmpty()) {
			return;
		}
		if (!password.equals(confirmPassword)) {
			FacesMessage msg = new FacesMessage("Confirm password does not match password");
			msg.setSeverity(FacesMessage.SEVERITY_ERROR);
			facesContext.addMessage(passwordId, msg);
			facesContext.renderResponse();
		}
		if (userEJB.findUserById(email) != null) {
			FacesMessage msg = new FacesMessage("User with this e-mail already exists");
			msg.setSeverity(FacesMessage.SEVERITY_ERROR);
			facesContext.addMessage(passwordId, msg);
			facesContext.renderResponse();
		}
	}
	public String register() {
		User user = new User(email, password, username);
                //System.out.println("The Registered Users");
		userEJB.createUser(user);
		log.log(Level.INFO, "New user created with e-mail: {0} and name: {1}", new Object[]{email, username});
		
                return "regdone.xhtml";
	}

    public static Logger getLog() {
        return log;
    }

    public static void setLog(Logger log) {
        RegisterView.log = log;
    }

    public UserEJB getUserEJB() {
        return userEJB;
    }

    public void setUserEJB(UserEJB userEJB) {
        this.userEJB = userEJB;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
	
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getConfirmPassword() {
		return confirmPassword;
	}
	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:mp="http://primefaces.org/ui/material"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">    
    <f:view>
        <h:head>       
            <h:outputStylesheet>           
            </h:outputStylesheet>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title><ui:insert name="title">CIMS</ui:insert></title>
            <style>
                h4{
                    font-family: sans-serif;
                    color: silver;
                    text-align=left;
                }
            </style> 
             
            <h:outputScript library="javax.faces" name="jsf.js" />
        </h:head>   

        <h:body>        
            
            <p:layout style="min-width:390px;min-height:30px;background-color:#040d8a;">
                <h4>CIMS Online</h4>  
            </p:layout>
            <p:outputPanel>
                <div class="ui-g">
                    <div class="ui-g-4"/>
                    <div class="ui-g-4">
                        <h:form id="login">
                            <p:growl id="msg" showDetail="true" life="3000" />
                            <h3><img src="loginLogo.JPG" alt=""/></h3>
                            <p:panel header="CIMS-Login" style="width: 390px; background-image: url('clasic card.jpg'); background-color: #040d8a" >

                                <p:messages id="messages" globalOnly="true"/>
                                <h:panelGrid columns="3" cellpadding="5" style="margin: 0 auto;">
                                    <h:outputLabel style='color:white' for="username" value="E-Mail"/>
                                    <h:inputText id="username" value="#{loginView.username}" required="true" requiredMessage="Please enter your e-mail address"/>
                                    <p:message for="username"/>
                                    <p:outputLabel style='color:white' for="password" value="Password"/>
                                    <h:inputSecret id="password" value="#{loginView.password}" required="true" requiredMessage="Please enter password"/>
                                    <p:message for="password"/>
                                    <p:commandButton id="submit" update="@form" 
                                                     value="Login" style="color: black" action="#{loginView.login}"/>
                                <h:link value="Register" outcome="/Register.xhtml" />
                                </h:panelGrid>
                            </p:panel>
                        </h:form>
                    </div>
                </div>
            </p:outputPanel>
        </h:body>
    </f:view>
</html>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<title>Register</title>
</h:head>
<h:body>
    <div class="centred-form">
    <h:form>
        <h:panelGrid styleClass="centred-form">
		
                <f:event listener="#{registerView.validatePassword}" type="postValidate"/>
                
		<h3>Create new account</h3>
		<h:panelGrid columns="2" styleClass="centred-form">
			<h:outputLabel for="username">Name:</h:outputLabel>
                        <h:inputText id="username" value="#{registerView.username}" required="true"
				requiredMessage="Please enter your name" maxlength="30"></h:inputText>
			<h:outputLabel for="email">E-Mail:</h:outputLabel>
                        <h:inputText id="email" value="#{registerView.email}" required="true"
				requiredMessage="Please enter your e-mail address">
				<f:validator validatorId="emailValidator" />
			</h:inputText>
			<h:outputLabel for="password">Password:</h:outputLabel>
                        <h:inputSecret id="password" value="#{registerView.password}"
				required="true" requiredMessage="Please enter password"
				validatorMessage="Password must contain atleast one lowercase character, 
					uppercase character, a digit and it's length must be between 6 and 20 characters">
				<f:validateRegex pattern="((?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,20})" />
			</h:inputSecret>
			<h:outputLabel for="confirmpassword">Confirm password:</h:outputLabel>
			<h:inputSecret id="confirmpassword"
                                       value="#{registerView.confirmPassword}" required="true"
				requiredMessage="Please confirm your password"></h:inputSecret>
                        <h:commandButton action="#{registerView.register()}" value="Register"></h:commandButton>
		</h:panelGrid>
                 </h:panelGrid>
	</h:form>
	<br />
	<br />
	<h:link value="I already have an account" outcome="login.xhtml" />
       </div>
   
</h:body>
</html>

**Comment by rieckpil** [comment]
closed as the duplicate. Please add the example to https://github.com/rieckpil/blog-tutorials/issues/5
