### ISSUE TITLE
Test a Spring MVC Thymeleaf View @Controller POST Endpoint

### ISSUE THREAD

**Issue by mimLau** [rieckpil/blog-tutorials#76]
## Blog post you are referring to

https://gitlab.com/mimLau/nurselink-web-client/-/blob/develop/src/test/java/com/lau/nurselink/webclient/webapp/controllers/AppHistoryStatusControllerTest.java

https://gitlab.com/mimLau/nurselink-web-client/-/blob/develop/src/main/java/com/lau/nurselink/webclient/webapp/controllers/AppHistoryStatusController.java

## Your Question

Hi, here is my question : 
In the first link you will find **AppHistoryStatusControllerTest class** where I want to test a **Post mapping** endpoint. I mocked **appHistoryStatusServiceMock**, and return an **appHistoryStatus**, but at controller side (AppHistoryStatusController class), **appHistoryStatus** was null. I tried to put appHistoryStatus in a **jsonRequest,** but still null. I added at controller side @RequestBody before the argument, the test successed but when I launched my application, the mapping was not working anymore, and I had this message error _"Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported"_.

Thank you !!

## Context (Environment, Dependency Versions, Framework)

 Java 11, spring boot, Windows 11, Thymeleaf

**Comment by mimLau** [comment]
**In the class test, I did my mockMvc.perform as following :**


  mockMvc.perform(post("/application/status/add")
                .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                .param("appStatus.statusName", appHistoryStatus.getAppStatus().getStatusName())
                .param("application.id", String.valueOf(app.getId()))
                .sessionAttr("appHistoryStatus", new AppHistoryStatusBean()))
                .andExpect(status().isFound())
                .andExpect(view().name("redirect:/institution/jobs/applications/job/" + app.getJob().getId()));
    }


**And in my controller, I added @ModelAttribute("appHistoryStatus") :**

 @PostMapping(value="/application/status/add")
    public String addAppHistoryStatus(@ModelAttribute("appHistoryStatus") AppHistoryStatusBean appHistoryStatus) {

        appHistoryStatusService.addAppHistoryStatus(appHistoryStatus);
        ApplicationBean app = applicationService.getAppById(appHistoryStatus.getApplication().getId());

        return "redirect:/institution/jobs/applications/job/" + app.getJob().getId();
    }

**Comment by rieckpil** [comment]
That's great that you found a solution by yourself @mimLau - I'm going to close the issue 👍
