### ISSUE TITLE
Issue with variable replacement for Docx4j

### ISSUE THREAD

**Issue by rieckpil** [rieckpil/blog-tutorials#9]
Hey Rieckpil,
This is my code I don’t know what I want to replace the variable with the collection

```
public class DocxGenerator {

    private static final String TEMPLATE_NAME = “template.dotx”;

    public byte[] generateDocxFileFromTemplate() throws Exception {

        InputStream templateInputStream = this.getClass().getClassLoader().getResourceAsStream(TEMPLATE_NAME);

        WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.load(templateInputStream);

        MainDocumentPart documentPart = wordMLPackage.getMainDocumentPart();

        List colorlist = new ArrayList();
        colorlist.add(“red”);
        colorlist.add(“white”);
        colorlist.add(“green”);

        VariablePrepare.prepare(wordMLPackage);

        java.util.HashMap variables = new java.util.HashMap();
        VariablePrepare.prepare(wordMLPackage);
        variables.put(“firstName”, “sathish”);
        variables.put(“lastName”, “kumar”);
        variables.put(“colorlist”, colorlist);

        documentPart.variableReplace(variables);

    }
}
```
My document template:

My name is ${firstName} ${lastName}
My favourite colors are ${colorlist}

**Comment by rieckpil** [comment]
I assume you can't replace the `${colorlist}` variable with a Java collection type as the `.variableReplace()` method of docx4j has the following signature `public void variableReplace(java.util.Map<String, String> mappings) throws JAXBException, Docx4JException` and is therefor expecting a `Map<String, String>`.

If you just want to render the content of your List, you can do the following:
```
 variables.put("colorlist", Arrays.asList("blue", "red", "white").stream().collect(Collectors.joining(", ")));
```

and the output on the document should be: `blue, red, white`.

Otherwise please have a look at the [library](https://github.com/plutext/docx4js) itself or ask the question again on [StackOverflow](https://stackoverflow.com/).

**Comment by sathish38** [comment]
> I assume you can't replace the `${colorlist}` variable with a Java collection type as the `.variableReplace()` method of docx4j has the following signature `public void variableReplace(java.util.Map<String, String> mappings) throws JAXBException, Docx4JException` and is therefor expecting a `Map<String, String>`.
> 
> If you just want to render the content of your List, you can do the following:
> 
> ```
>  variables.put("colorlist", Arrays.asList("blue", "red", "white").stream().collect(Collectors.joining(", ")));
> ```
> 
> and the output on the document should be: `blue, red, white`.
> 
> Otherwise please have a look at the [library](https://github.com/plutext/docx4j) itself or ask the question again on [StackOverflow](https://stackoverflow.com/).

Hi rieckpil,
I want to iterate it by one by one like this
1.blue
2.red
3.white
what I want to do change in my template so far I used the foreach in the template but it doesnt works
